services: 
  db: 
    container_name: postgres_container
    image: postgres:16
    ports:
      - 5000:5432
    environment: 
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes: 
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/airflow_init.sql:/docker-entrypoint-initdb.d/airflow_init.sql
    networks:
      - first-network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./pgadmin/data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - first-network


  airflow: 
    container_name: airflow_container
    image: apache/airflow:latest
    ports:
      - 8000:8080
    environment: 
      AIRFLOW_DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@db:5432/airflow_db
    volumes: 
      - ./airflow/dags:/opt/airflow/dags
      - ./api_request:/opt/airflow/api_request
    depends_on: 
      - db
    networks: 
      - first-network
    command: >
      bash -c "airflow db migrate && airflow standalone"

  dbt:
    container_name: dbt_container
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
    volumes: 
      - ./dbt/my_project:/user/app
    working_dir: /user/app
    environmnent: 
      DBT_PROFILES_DIR: "/root/.dir"
    depends_on: 
      - db
    networks:
      - first-network
    command: debug #init my_project

networks: 
  first-network: 
    driver: bridge